<?php

use App\Models\AcademicDegree;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->academicDegree = AcademicDegree::factory()->create();
});

test('to array', function () {
    expect(array_keys($this->academicDegree->toArray()))->toBe([
        'title', 'updated_at', 'created_at', 'id',
    ]);
});

it('belongs to many presenters', function () {
    expect($this->academicDegree->presenters())->toBeInstanceOf(HasMany::class);
});
