<?php

use App\Models\Chapter;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->chapter = Chapter::factory()->create();
});

test('to array', function () {
    expect(array_keys($this->chapter->toArray()))->toBe([
        'title', 'position', 'parent_id', 'series_id', 'default', 'updated_at', 'created_at', 'id',  'series',
    ]);
});

it('belongs to a series', function () {
    expect($this->chapter->series())->toBeInstanceOf(BelongsTo::class);
});

it('has many clips', function () {
    expect($this->chapter->clips())->toBeInstanceOf(HasMany::class);
});
