<?php

use App\Models\Comment;
use App\Models\User;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->comment = Comment::factory()->create();
});

test('to array', function () {
    expect(array_keys($this->comment->toArray()))->toBe([
        'content', 'owner_id', 'type', 'commentable_type', 'commentable_id', 'updated_at', 'created_at', 'id',
    ]);
});

it('belongs to a clip', function () {
    expect($this->comment->commentable())->toBeInstanceOf(BelongsTo::class);
});

it('belongs to a series', function () {
    expect($this->comment->commentable())->toBeInstanceOf(BelongsTo::class);
});

it('belongs to an owner', function () {
    expect($this->comment->owner)->toBeInstanceOf(User::class);
});
