<?php

use App\Models\Document;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->document = Document::factory()->create();
});

test('to array', function () {
    expect(array_keys($this->document->toArray()))->toBe(['name', 'save_path',   'updated_at', 'created_at', 'id']);
});

it('may have many series', function () {
    expect($this->document->series())->toBeInstanceOf(MorphToMany::class);
});

it('may have many clips', function () {
    expect($this->document->clips())->toBeInstanceOf(MorphToMany::class);
});
